### ISSUE TITLE
Add Logging to Meta-Data Fetch process

### ISSUE THREAD

**Issue by levi-turner** [eapowertools-archive/qs-telemetry-dashboard-node#44]
**Issue:** Currently there is no logging of the meta-data fetch process which makes troubleshooting difficult.

**Current method:** Launch the fetchMetadata.js script manually. Example in cmd.exe with default install locations:
cd "C:\Program Files\Qlik\Sense\ServiceDispatcher\Node"
Node.exe "C:\Program Files\Qlik\Sense\EAPowerTools\TelemetryDashboard\fetchMetadata.js"

**Comment by Balasupreetha** [comment]
Hi, I see the csv files do not generate at all. What and where should i check if there are errors while generation?

**Comment by levi-turner** [comment]
See my comment on your issue.

**Comment by jparis** [comment]
fixed with new version of Telemetry. Official release coming very soon: https://github.com/eapowertools/qs-telemetry-dashboard
