### ISSUE TITLE
Expose User Name as well as UserId in fetch process

### ISSUE THREAD

**Issue by levi-turner** [eapowertools-archive/qs-telemetry-dashboard-node#50]
In `getUsers.js`, the call is to grab the user's id, userId, and userDirectory:
```
                    dataRow.push(element['id']);
                    dataRow.push(element['userId']);
                    dataRow.push(element['userDirectory']);
```
Adding `name` will enhance the use in larger environments where the `userId` value is often programmatically generated and functionally meaningless.

It would still require a user to swap out the dimension in the app, but providing it as an option enhances usability.

After:
```
                    dataRow.push(element['id']);
                    dataRow.push(element['userId']);
					dataRow.push(element['name']);
                    dataRow.push(element['userDirectory']);
```

Would also require pulling the `users.csv` into the Metadata section of the load script as it is currently unused

**Comment by levi-turner** [comment]
Abandoned.

**Comment by jparis** [comment]
fixed with new version of Telemetry. Official release coming very soon: https://github.com/eapowertools/qs-telemetry-dashboard
