### ISSUE TITLE
Add incremental loading log to the App Metadata Fetch reload

### ISSUE THREAD

**Issue by levi-turner** [eapowertools-archive/qs-telemetry-dashboard-node#52]
**Issue:** Add incremental loading log to the App Metadata Fetch reload

**Rationale:** At large app volumes, this reload can take 8+ hours.

**Comment by levi-turner** [comment]
Closing due to improvements on v3.0.0 release

**Comment by ken4runner** [comment]
can you confirm if incremental load has been fully implemented for this? each reload seems to take about the same amount of time in our environment.

**Comment by levi-turner** [comment]
@ken4runner : Now that you mention it, I don't believe this improvement as implemented. @jparis

**Comment by levi-turner** [comment]
Confirmed with @jparis this has not been implemented.

**Comment by levi-turner** [comment]
@jparis : To confirm:

- When you change an object in a sheet, does the `modifiedTime` in the `/qrs/app/object` entity get reliably updated?

**Comment by levi-turner** [comment]
@ken4runner : How long does the app metadata fetch process take for you all to reload?

**Comment by gorkor** [comment]
@levi-turner : For us it takes close to 5 hours.
Incremental feature would be much appreciated! 

what's happening between apps.csv and visualizations.csv is written, is what takes time...

<img width="582" alt="Screenshot 2020-05-05 at 08 48 46" src="https://user-images.githubusercontent.com/23354247/81041234-9f38af00-8ead-11ea-8cd9-02f914fecee3.png">

**Comment by levi-turner** [comment]
@gorkor : Yes. We are working on it. It's basically loading every app, every sheet, and parsing every visualization. Using some rough maths your environment has ~3.2k apps. We're working on doing an incremental check for only changed apps.

**Comment by gorkor** [comment]
@levi-turner :  3489 and counting...

**Comment by jparis** [comment]
fixed with new version of Telemetry. Official release coming very soon: https://github.com/eapowertools/qs-telemetry-dashboard
