### ISSUE TITLE
Parse Physical and calculated Working Sets from all nodes

### ISSUE THREAD

**Issue by levi-turner** [eapowertools-archive/qs-telemetry-dashboard-node#58]
**Issue**: Currently the app pulls the RAM usage from a NodeJS call which means that RAM is calculated solely for the node doing the reload.

**Where is the data present:** 
* Repository > System
* Message column
* Like so: `Total amount of   system physical RAM available is: 274841600000 (255.97 GB(s))`

**Comment by jparis** [comment]
fixed with new version of Telemetry. Official release coming very soon: https://github.com/eapowertools/qs-telemetry-dashboard
