### ISSUE TITLE
QIX Performance Log Level Null with multiple log levels

### ISSUE THREAD

**Issue by levi-turner** [eapowertools-archive/qs-telemetry-dashboard-node#79]
When there are varying values for qixPerformanceLogVerbosity generated from `getLogLevels.js`, the KPI on the *Introduction* sheet is shown as null.

Script: `=Only({<LogType={'qixPerformanceLogVerbosity'}>} LogLevel)`

Fixed: `=MinString({<LogType={'qixPerformanceLogVerbosity'}>} LogLevel)`

**Comment by Justformoment** [comment]
Dear @levi-turner ,

When I update status of QIX Performance Log Level on Central Engine node to Warning. In Telemetry Dashboard app, it still says status of QIX is Off. 


![qix](https://user-images.githubusercontent.com/26446355/66116141-8348f400-e5d2-11e9-9bf7-17342db8b996.PNG)
![qix2](https://user-images.githubusercontent.com/26446355/66116142-8348f400-e5d2-11e9-9c83-969620e0fd51.PNG)
![qix3](https://user-images.githubusercontent.com/26446355/66116144-83e18a80-e5d2-11e9-834a-c65005276f62.PNG)

**Comment by levi-turner** [comment]
Have you subsequently:

1. Reloaded the metadata
2. Reloaded the Qlik app?

Because this value is generated from one of the meta-data fetch's modules.

**Comment by Justformoment** [comment]
Thank you very much, now it works
