### ISSUE TITLE
Specified path unavailable

### ISSUE THREAD

**Issue by tesgo** [eapowertools-archive/qs-telemetry-dashboard-node#81]
Hello,

The root folder of my Qlik Sense Server is like (Azure File Share) : \\xxxxxx.file.core.windows.net\nas-qliksense\File_Share\QlikShare

I specified this path for Telemetry Dashboard install

But the Telemetry Dashboard does not accept this path and the installation program stop with an error

Best Regards

**Comment by jparis** [comment]
What error do you specifically see? Can you post a screenshot of the path in the installer and the error? thanks.

**Comment by tesgo** [comment]
![Capture](https://user-images.githubusercontent.com/23262119/65975498-fcc7d180-e46e-11e9-8902-74a72c129347.PNG)
![Capture2](https://user-images.githubusercontent.com/23262119/65975606-2680f880-e46f-11e9-8e9e-ad5913df7dae.PNG)

**Comment by tesgo** [comment]
Hello
I use the service accout of Qlik Sense Server to install "Telemetry Dashboard"
This account has acces to the share and is full admin of the server
Regards

**Comment by jparis** [comment]
Can you run the msi with loggin then post it here?

Run the following in an admin command prompt with the correct values:
`msiexec /i "C:\MyPackage\Example.msi" /L*V "C:\log\example.log"`

**Comment by tesgo** [comment]
Hi Jesse

You can find the error

MSI (c) (58:58) [16:04:52:267]: Note: 1: 2205 2:  3: Error 
MSI (c) (58:58) [16:04:52:267]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 2898 
Info 2898.For WixUI_Font_Title textstyle, the system created a 'Tahoma' font, in 0 character set, of 14 pixels height.
Action 16:04:52: LicenseAgreementDlg. Dialog created
MSI (c) (58:58) [16:04:53:672]: PROPERTY CHANGE: Adding LicenseAccepted property. Its value is '1'.
Action 16:04:54: InstallDirDlg. Dialog created
MSI (c) (58:58) [16:05:18:399]: Note: 1: 1314 2: \\cdcqliknasdev.file.core.windows.net\nas-qliksense\File_Share\QlikShare\TelemetryDashboard\ 
MSI (c) (58:58) [16:05:18:401]: Note: 1: 2205 2:  3: Error 
MSI (c) (58:58) [16:05:18:401]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1314 
Error 1314. The specified path '\\cdcqliknasdev.file.core.windows.net\nas-qliksense\File_Share\QlikShare\TelemetryDashboard\' is unavailable.
MSI (c) (58:58) [16:07:26:687]: Note: 1: 2205 2:  3: Error 
MSI (c) (58:58) [16:07:26:687]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
MSI (c) (58:58) [16:07:26:687]: Product: TelemetryDashboard -- Error 1314. The specified path '\\xxxxx
qliknasdev.file.core.windows.net\nas-qliksense\File_Share\QlikShare\TelemetryDashboard\' is unavailable.


[example.log](https://github.com/eapowertools/qs-telemetry-dashboard/files/3697817/example.log)

**Comment by jparis** [comment]
Any idea why there's only a single leading backslash for the path? Are you copy/pasting it, that seems weird as it should be `\\_____`

**Comment by tesgo** [comment]
The second backslash is cutted by "GitHub"
You can find a screenshot of the error message : there is two backslash

![image](https://user-images.githubusercontent.com/23262119/66409131-68221e00-e9f0-11e9-80fd-a35447f1142b.png)

**Comment by EmanueleF82** [comment]
Hello,
I have the same problem using the Azure Storage account.
Do you have any update about this issue?

Best regards,
E.

**Comment by jparis** [comment]
Sorry for the slow reply. Looking into this and trying to come up with a solution in the installer.

**Comment by withdave** [comment]
@jparis - Same problem here. Tried adding the creds to the SYSTEM account using PsExec but didn't solve it, might need a user elevation option on the installer?

**Comment by jparis** [comment]
It's actually an internal msi validation step. My guess is that because the hostname isn't available, it just fails instantly. Given that normally you don't run installers against shares, I think it checks root to make sure it's valid, before it tries to validate the path.

Going to try to rewrite the path dialogue screen so no build-in validation runs. Will report back if this works. Levi set up an environment for me with a Azure fileshare I can test on.

**Comment by EmanueleF82** [comment]
hello
did you find a solution to solve the issue?

Many thanks
E.

**Comment by jparis** [comment]
Will report back next week.

**Comment by jparis** [comment]
fixed with new version of Telemetry. Official release coming very soon: https://github.com/eapowertools/qs-telemetry-dashboard
