### ISSUE TITLE
Version 3 Instalation error "Index and length must refer to a location withon the srting

### ISSUE THREAD

**Issue by strelokr** [eapowertools-archive/qs-telemetry-dashboard-node#88]
I have a question. Try to isntall Telemetrydashboard version 3 and faced with error "Index and length must refer to a location withon the srting.
Parameter name: length"
instalation path is short \\qsdemo\Sense\TelemetryDashboard\

**Comment by levi-turner** [comment]
Is the installer being launched with local admin rights? If you're unsure, then launch `cmd.exe` with admin rights then execute the installer in that context.

**Comment by strelokr** [comment]
Hello Levi,
yes, I have admin rights. And I try to run from cmd.exe with administrator rights - result the same
And my user  can write to \\qsdemo\Sense\ folder

**Comment by levi-turner** [comment]
What is `qsdemo`? Is this a local share? Something else?

**Comment by strelokr** [comment]
Yes \\qsdemo\qlikshare it's share folder on the same Windows machine

**Comment by levi-turner** [comment]
And the user has full control over both the share and the folder at the NT level?

**Comment by strelokr** [comment]
Yeap, I double chech it. Full NTFS rights and R/W rights on share

**Comment by mufaddalb** [comment]
I get the same error and have full rights to the network folder

**Comment by AngelaShao** [comment]
I get the same error and can’t uninstallation and repair.  the Telemetrydashboard new version 3.1.0, the old broken version is 2.0.1.0.
![image](https://user-images.githubusercontent.com/21167129/71389512-a31f0f80-2637-11ea-818d-7f7fcf311d8a.png)
![image](https://user-images.githubusercontent.com/21167129/71389521-a914f080-2637-11ea-9e6a-9bf79d9266ec.png)
![image](https://user-images.githubusercontent.com/21167129/71389525-ad410e00-2637-11ea-8e09-05be6e4ef46f.png)

**Comment by levi-turner** [comment]
@jparis : Any sense of whether the installer improvements that you're planning may address this? Or do we need to dig into how to manually uninstall the old version?

**Comment by jparis** [comment]
fixed with new version of Telemetry. Official release coming very soon: https://github.com/eapowertools/qs-telemetry-dashboard
