### ISSUE TITLE
Visualizations table shows objects that no longer exist

### ISSUE THREAD

**Issue by bchastain** [eapowertools-archive/qs-telemetry-dashboard-node#92]
I am using the telemetry dashboard to create the data for the Extensions Usage Dashboard, and I noticed I was seeing extensions being used in apps where they had been deleted.

I checked the raw Telemetry visualizations.csv file and for some apps it shows visualizations in sheets that are no longer there. I've re-run the data refresh on Telemetry to no avail. I've double-checked the app to make sure it's not a hidden master item or anything, but that visualization is definitely no longer there, yet it shows up in the CSV.

**Comment by levi-turner** [comment]
@jparis : Thoughts?

**Comment by jparis** [comment]
That's super bizarre. The csv pulls data from the engine, so for some reason the engine must assume the extension is still there for some reason.

Is there an app you can scrape clean and send that I can test with?

**Comment by bchastain** [comment]
I duplicated one of the false positive apps and stripped everything out of it and it still shows as having a "cl-container" object in it in the Telemetry files


[False Positive.zip](https://github.com/eapowertools/qs-telemetry-dashboard/files/4376643/False.Positive.zip)

**Comment by levi-turner** [comment]
I guess I am not exactly following here. In the `False Positive.qvf` file there is a single sheet. Inside that single sheet there is a single visualization. That visualization is pulling from an extension object (`Utility: VizLib Text Object (VizlibTextObject`):

![image](https://user-images.githubusercontent.com/23237561/77455965-f472a280-6dd0-11ea-9e4b-1bc6957fdb97.png)
* **Note**  the viz is re-sized for clarity. It's actually a 1x1 cell in the bottom left-hand corner:
![image](https://user-images.githubusercontent.com/23237561/77456056-153af800-6dd1-11ea-916a-ba73f258238b.png)

So back to the original issue here, my expectation is that the Telemetry Meta-Data Fetch would (a) see the visualization object and the Extension Dashboard would (b) flag this visualization as being an extension.

Are (a) and/or (b) not happening?

**Comment by bchastain** [comment]
Oh I didn't even see that one in there, but that's not the Object that's showing up as a false positive. I stripped everything (except that one Text object) out, but Telemetry is still reporting there's a Climber container viz in there (cl-container is the extension name).

**Comment by zucoa** [comment]
@levi-turner thanks for looking into this, do you have an idea what may be causing removed extensions to still show as @bchastain reports? We're unable to move off of the June release until we start deprecating. Thanks!

**Comment by levi-turner** [comment]
`SheetID` in the `visualizations.csv` needs to be turned into a composite key of `appid|sheetid` for uniqueness reasons.

**Comment by ng867** [comment]
I am also facing same issues with Vizlib extensions.
I completely removed all the vizlib objects from sheet , but metadata fetcher is still pulling data that its available in the sheet.
DO you have any idea by when it may be resolved...

**Comment by levi-turner** [comment]
@ng867 : Please reach out to me directly (`MyFirstName.MyLastName@qlik.com`) for more instruction here. For the known problem(s) the fix requires editing one of the JavaScript files which is deployed as a part of the package so I'd prefer to have direct correspondence until this fix can be delivered as part of the installation process.

**Comment by jparis** [comment]
engine issue.
