### ISSUE TITLE
SheetName and SheetId fields show sheets not in app

### ISSUE THREAD

**Issue by SusanHS** [eapowertools-archive/qs-telemetry-dashboard-node#94]
We first found from dashboard that an app has some sheets that it doesn't have. After checking the metadata csv files and QIXPerformance_engine log, we found that one ObjectId may have multiple SheetId (in visualization table). One SheetId may also have multiple SheetName (in sheets table). Therefore, each row in fact table (QIXPerformance_Engine) are duplicated by amount of SheetIds & SheetNames. It would be nice to fix this, as this causes confusion to our consultants.

**Comment by levi-turner** [comment]
I believe this will be fixed in the next release.

**Comment by SusanHS** [comment]
Great! Looking forward to the next release! :-)

**Comment by SusanHS** [comment]
Do we have any estimation when the new version will be released?

**Comment by jparis** [comment]
fixed with new version of Telemetry. Official release coming very soon: https://github.com/eapowertools/qs-telemetry-dashboard
