### ISSUE TITLE
Unable to uninstall QS Telemetry dashboard on multi node server.

### ISSUE THREAD

**Issue by sanket8397** [eapowertools-archive/qs-telemetry-dashboard-node#96]
Hi,

I am trying to unistall QS Telemetry dashboard v3.0.0 in order to install latest version of telemetry dashboard.
When I am trying to uninstall dashboard from control panel , it is doing rollback.
When I am trying to install latest version of dashboard , it goes till last step , and then start doing rollback.

Please suggest.

Thank you.

**Comment by levi-turner** [comment]
Can you provide the installer log from %TEMP% (https://youtu.be/EPLl1BODwH4?t=177)?

**Comment by sanket8397** [comment]
Hi Levi , I cant provide you log file. But if you need any specific details. I can provide that.
Is there any reason , that I am not able to uninstall previous version of dashboard.
Thank you.

**Comment by levi-turner** [comment]
What do you mean you cannot provide the log file? Is that because the log file does not exist? Some other reason?

**Comment by levi-turner** [comment]
@sanket8397 : What do you mean you cannot provide the log file? Is that because the log file does not exist? Some other reason?

**Comment by sanket8397** [comment]
@levi-turner  It was access issue. I  was unable to access certificates Repository.

**Comment by sanket8397** [comment]
@levi-turner  
I have one silly doubt.
We have 2 Nodes : Central Node and Backup Node.
And both are pointing to same root folder in service cluster.
We only need to install it on CENTRAL node , right ?
And what we should to install it on backup node as well.

Thank you.

**Comment by levi-turner** [comment]
So the Telemetry Dashboard uses a copy of the internal certificates used by Qlik Sense for inter-service communication. All copies in a cluster come from a common Root Certificate and thus are trusted for this exchange. Insofar as all nodes use certificates from the same common root, then it's fine. It's a bit unclear what a backup node is.

**Comment by levi-turner** [comment]
Fixed by access rights to the certs directory
