### ISSUE TITLE
I am seeing a strange issue when visualization & Sheets.csv is not updating

### ISSUE THREAD

**Issue by sujithgudipudi** [eapowertools-archive/qs-telemetry-dashboard-node#99]
I have installed latest version of telemetry and after reloading the task visualization & Sheets.csv is not updating and task is completing successfully.
![image](https://user-images.githubusercontent.com/45575405/87611520-461f9f80-c6d6-11ea-9842-e970ce528a05.png)

**Comment by jparis** [comment]
Hopefully fixed with new version of Telemetry. Official release coming very soon: https://github.com/eapowertools/qs-telemetry-dashboard
